name: Generate and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Generate documentation
      - name: Generate documentation
        run: dart doc .

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/api